# Generated by Django 3.1.6 on 2021-02-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_post_id', models.TextField()),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('body', models.TextField()),
                ('created_utc', models.IntegerField()),
                ('num_comments', models.IntegerField()),
                ('image', models.TextField()),
            ],
        ),
    ]
